### PR TITLE
Fix documentation: Add interface EditorStateConfig

### PR DESCRIPTION
**Pull request by timjb**
This enables [getdocs2ts](https://github.com/bradleyayers/getdocs2ts) to generate better type signatures.

### CODE REVIEW

**Comment by marijnh** [comment]
I'm not sure unifying these is a good idea -- `doc` and `selection` are meaningless in `fromJSON`, since they'll be read from the JSON data.

**Comment by timjb** [comment]
I've adapted the documentation, using `EditorStateConfig` only for `create` and `reconfigure`.

By the way, I think the documentation for `reconfigure` is a bit misleading, since the code of `reconfigure` seems to do more than just adjust the set of active plugins. Rather, it creates a whole new `EditorState` based on the given options (e.g. `schema`), preserving the state of plugins that are already present.

**Comment by marijnh** [comment]
Would it make sense to simply fold `EditorStateConfig` into the doc comment for `create` again now, since it's only referenced in one place, and the docs are probably easier to read if they don't require jumping to another named type to figure out the options?

> Rather, it creates a whole new EditorState

Since these are persistent objects, I think it is self evident that it will create a new object. Which part surprised you?

**Comment by timjb** [comment]
> [...] since it's only referenced in one place

No, it's referenced in two places, `reconfigure` and `create`, but see below.
There's one other place where this type maybe would make sense: `StateField.init`

> Which part surprised you?

Ok, I've had another look at the code of `reconfigure` and I think that I had misunderstood it previously. I now see that the only options that can be reconfigured are `plugins`, `schema` and maybe other options defined by plugins. (I had thought that one can also reconfigure, for example, `doc` and `selection`.) Realizing this, it makes sense to not use `EditorStateConfig` and declare the possible properties of `options` inline.

I've added two new commits inlining the type declarations of `options` for `create` and `reconfigure`.

**Comment by marijnh** [comment]
Thanks! Merged as 877cba1

**Pull request closed without merging**
